In [1]:
import numpy as np

### 행렬의 차원 변경 
- 1차원 행렬 -> 다차원 행렬
- 다차원 행렬 -> 1차원 행렬

In [2]:
# 1차원 행렬을 생성한다.
array1 = np.arange(15)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
# 행렬의 차원 정보
# 1차원 행렬인 경우 행렬이 관리하는 원소의 개수를 튜플에 담아 반환해준다.
a1 = array1.shape
a1

(15,)

In [4]:
# 1차원 -> 다차원
# 새롭게 생성할 행열 구조를 작성해준다.
array2 = array1.reshape(3, 5)
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# 14개의 원소를 가지고 있는 1차원 행렬을 3행 5열 행렬로 변환
array3 = np.arange(14)
# 행렬에서 모든 행은 열의 개수가 동일해야 한다 (수학에서 정의한 행렬 성립의 기본 조건 중 하나)
# 이에 3행 5열짜리 행열을 구성하려면 15개의 원소가 필요하지만 부족하기 때문에 오류가 발생한다.
array4 = array3.reshape(3, 5)

In [ ]:
# 16개의 원소를 가지고 있는 1차원 행렬을 3행 5열 행렬로 변환
array3 = np.arange(16)
# 행렬에서 모든 행은 열의 개수가 동일해야 한다 (수학에서 정의한 행렬 성립의 기본 조건 중 하나)
# 이에 3행 5열짜리 행열을 구성하려면 15개의 원소가 필요하지만 남기 때문에 오류가 발생한다.
array4 = array3.reshape(3, 5)

In [6]:
# 다차원 행렬을 1차원으로 변환한다.
array1 = np.arange(15).reshape(3, 5)

# 행렬의 원소의 개수를 넣어준다
array2 = array1.reshape(15)
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# 만약 원소의 개수를 많거나 적게 넣어주면 오류가 발생한다.
array3 = array1.reshape(16)

In [7]:
# 다차원 행렬을 1차원으로 바꾸고 싶을 때 원소의 개수 대신 -1을 넣어주면
# 알아서 원소의 개수를 계산하여 변환해준다.
array2 = array1.reshape(-1)
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
# 1차원 행렬을 다차원 행렬로 변환하고자 할 때도 -1 을 사용할 수 있다.
# 행의 수를 결정해주고 -1을 열에 넣어주면 열의 개수가 자동 계산된다.
# 열의 수를 결정해주고 -1을 행에 넣어주면 행의 개수가 자동 계산된다.
array3 = array1.reshape(3, -1)
array4 = array1.reshape(-1, 3)

display(array3)
display(array4)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
# 아무리 -1을 넣어준다고 하더라도 만들어진 행렬의 모든 행이 동일한 열의 개수를 가질 수가 없다면
# 오류가 발생한다
array1 = np.arange(14)
array2 = array1.reshape(3, -1)

### 행렬 정보

In [9]:
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [10]:
# 행렬의 차원의 수
print(array1.ndim)
print(array2.ndim)

1
2


In [11]:
# 행과 열의 수
print(array1.shape)
print(array2.shape)

(5,)
(2, 3)


In [12]:
# 전체 원소의 개수
print(array1.size)
print(array2.size)

5
6


In [13]:
# 행렬이 관리하는 값들의 타입
print(array1.dtype)
print(array2.dtype)

int64
int64


### 통계함수 
- 통계함수의 종류는 pandas에서 다루도록 하겠습니다.

In [14]:
array1 = np.arange(15).reshape(3, 5)
array1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
# 행렬.함수()
# 행렬이 가지고 있는 값을 통해 통계 값을 구한다.
a1 = array1.mean()
a2 = array1.max()
a3 = array1.min()

print(a1, a2, a3)

7.0 14 0


In [16]:
# 행별 통계
a1 = array1.mean(axis=1)
a2 = array1.max(axis=1)
a3 = array1.min(axis=1)

print(a1, a2, a3)

[ 2.  7. 12.] [ 4  9 14] [ 0  5 10]


In [17]:
# 열별 통계
a1 = array1.mean(axis=0)
a2 = array1.max(axis=0)
a3 = array1.min(axis=0)

print(a1, a2, a3)

[5. 6. 7. 8. 9.] [10 11 12 13 14] [0 1 2 3 4]


In [18]:
# numpy.함수
a1 = np.mean(array1)
a2 = np.mean(array1, axis=1)
a3 = np.mean(array1, axis=0)

print(a1, a2, a3)

7.0 [ 2.  7. 12.] [5. 6. 7. 8. 9.]


In [19]:
# numpy.함수() 방식의 통계 함수들은 다른 것들을 통해 통계값을 계산할 수 있도록
# 추가로 제공하는 함수들이다.
a1 = [10, 20, 30]
a2 = (10, 20, 30)

v1 = np.mean(a1)
v2 = np.mean(a2)

print(v1, v2)

20.0 20.0
